spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/quincycopeland
    username: ${DB_USERNAME} # ENV variable for my data source
    password: ${DB_PASSWORD} # EBV variable for db password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false